2024-09-24 11:39:41,974 * INFO * 'test_challenge' выполнен успешно
2024-09-24 11:39:41,974 * WARNING * 'test_run'. Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "C:\Users\User\PycharmProjects\pythonProject2\Module_12\tests_12_4.py", line 88, in test_run
    second = Runner(123, 5)
             ^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\pythonProject2\Module_12\tests_12_4.py", line 11, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2024-09-24 11:39:41,975 * WARNING * 'test_walk'. Неверная скорость для Runner
Traceback (most recent call last):
  File "C:\Users\User\PycharmProjects\pythonProject2\Module_12\tests_12_4.py", line 74, in test_walk
    first = Runner("Вася", -10)
            ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\pythonProject2\Module_12\tests_12_4.py", line 16, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -10
